<?php

add_filter('reuse_icon_picker', 'userplace_dashicons', 2, 1);

function userplace_dashicons($icons)
{

    $icons[] = array(
        'label' => esc_html__('Dashicons', 'userplace'),
        'value' => 'dashicons',
        'icons' => array(
            array('name' => 'menu', 'className' => 'dashicons dashicons-menu'),
            array('name' => 'site', 'className' => 'dashicons dashicons-admin-site'),
            array('name' => 'dashboard', 'className' => 'dashicons dashicons-dashboard'),
            array('name' => 'post', 'className' => 'dashicons dashicons-admin-post'),
            array('name' => 'media', 'className' => 'dashicons dashicons-admin-media'),
            array('name' => 'links', 'className' => 'dashicons dashicons-admin-links'),
            array('name' => 'page', 'className' => 'dashicons dashicons-admin-page'),
            array('name' => 'comments', 'className' => 'dashicons dashicons-admin-comments'),
            array('name' => 'appearance', 'className' => 'dashicons dashicons-admin-appearance'),
            array('name' => 'plugins', 'className' => 'dashicons dashicons-admin-plugins'),
            array('name' => 'users', 'className' => 'dashicons dashicons-admin-users'),
            array('name' => 'tools', 'className' => 'dashicons dashicons-admin-tools'),
            array('name' => 'settings', 'className' => 'dashicons dashicons-admin-settings'),
            array('name' => 'network', 'className' => 'dashicons dashicons-admin-network'),
            array('name' => 'home', 'className' => 'dashicons dashicons-admin-home'),
            array('name' => 'generic', 'className' => 'dashicons dashicons-admin-generic'),
            array('name' => 'collapse', 'className' => 'dashicons dashicons-admin-collapse'),
            array('name' => 'filter', 'className' => 'dashicons dashicons-filter'),
            array('name' => 'customizer', 'className' => 'dashicons dashicons-admin-customizer'),
            array('name' => 'multisite', 'className' => 'dashicons dashicons-admin-multisite'),
            array('name' => 'write blog', 'className' => 'dashicons dashicons-welcome-write-blog'),
            array('name' => 'add page', 'className' => 'dashicons dashicons-welcome-add-page'),
            array('name' => 'view site', 'className' => 'dashicons dashicons-welcome-view-site'),
            array('name' => 'widgets and menus', 'className' => 'dashicons dashicons-welcome-widgets-menus'),
            array('name' => 'comments', 'className' => 'dashicons dashicons-welcome-comments'),
            array('name' => 'learn more', 'className' => 'dashicons dashicons-welcome-learn-more'),
            array('name' => 'aside', 'className' => 'dashicons dashicons-format-aside'),
            array('name' => 'image', 'className' => 'dashicons dashicons-format-image'),
            array('name' => 'gallery', 'className' => 'dashicons dashicons-format-gallery'),
            array('name' => 'video', 'className' => 'dashicons dashicons-format-video'),
            array('name' => 'status', 'className' => 'dashicons dashicons-format-status'),
            array('name' => 'quote', 'className' => 'dashicons dashicons-format-quote'),
            array('name' => 'chat', 'className' => 'dashicons dashicons-format-chat'),
            array('name' => 'audio', 'className' => 'dashicons dashicons-format-audio'),
            array('name' => 'camera', 'className' => 'dashicons dashicons-camera'),
            array('name' => 'images (alt)', 'className' => 'dashicons dashicons-images-alt'),
            array('name' => 'images (alt 2)', 'className' => 'dashicons dashicons-images-alt2'),
            array('name' => 'video (alt)', 'className' => 'dashicons dashicons-video-alt'),
            array('name' => 'video (alt 2)', 'className' => 'dashicons dashicons-video-alt2'),
            array('name' => 'video (alt 3)', 'className' => 'dashicons dashicons-video-alt3'),
            array('name' => 'archive', 'className' => 'dashicons dashicons-media-archive'),
            array('name' => 'audio', 'className' => 'dashicons dashicons-media-audio'),
            array('name' => 'code', 'className' => 'dashicons dashicons-media-code'),
            array('name' => 'default', 'className' => 'dashicons dashicons-media-default'),
            array('name' => 'document', 'className' => 'dashicons dashicons-media-document'),
            array('name' => 'interactive', 'className' => 'dashicons dashicons-media-interactive'),
            array('name' => 'spreadsheet', 'className' => 'dashicons dashicons-media-spreadsheet'),
            array('name' => 'text', 'className' => 'dashicons dashicons-media-text'),
            array('name' => 'video', 'className' => 'dashicons dashicons-media-video'),
            array('name' => 'audio playlist', 'className' => 'dashicons dashicons-playlist-audio'),
            array('name' => 'video playlist', 'className' => 'dashicons dashicons-playlist-video'),
            array('name' => 'play player', 'className' => 'dashicons dashicons-controls-play'),
            array('name' => 'player pause', 'className' => 'dashicons dashicons-controls-pause'),
            array('name' => 'player forward', 'className' => 'dashicons dashicons-controls-forward'),
            array('name' => 'player skip forward', 'className' => 'dashicons dashicons-controls-skipforward'),
            array('name' => 'player back', 'className' => 'dashicons dashicons-controls-back'),
            array('name' => 'player skip back', 'className' => 'dashicons dashicons-controls-skipback'),
            array('name' => 'player repeat', 'className' => 'dashicons dashicons-controls-repeat'),
            array('name' => 'player volume on', 'className' => 'dashicons dashicons-controls-volumeon'),
            array('name' => 'player volume off', 'className' => 'dashicons dashicons-controls-volumeoff'),
            array('name' => 'crop', 'className' => 'dashicons dashicons-image-crop'),
            array('name' => 'rotate', 'className' => 'dashicons dashicons-image-rotate'),
            array('name' => 'rotate left', 'className' => 'dashicons dashicons-image-rotate-left'),
            array('name' => 'rotate right', 'className' => 'dashicons dashicons-image-rotate-right'),
            array('name' => 'flip vertical', 'className' => 'dashicons dashicons-image-flip-vertical'),
            array('name' => 'flip horizontal', 'className' => 'dashicons dashicons-image-flip-horizontal'),
            array('name' => 'filter', 'className' => 'dashicons dashicons-image-filter'),
            array('name' => 'undo', 'className' => 'dashicons dashicons-undo'),
            array('name' => 'redo', 'className' => 'dashicons dashicons-redo'),
            array('name' => 'bold', 'className' => 'dashicons dashicons-editor-bold'),
            array('name' => 'italic', 'className' => 'dashicons dashicons-editor-italic'),
            array('name' => 'ul', 'className' => 'dashicons dashicons-editor-ul'),
            array('name' => 'ol', 'className' => 'dashicons dashicons-editor-ol'),
            array('name' => 'quote', 'className' => 'dashicons dashicons-editor-quote'),
            array('name' => 'alignleft', 'className' => 'dashicons dashicons-editor-alignleft'),
            array('name' => 'aligncenter', 'className' => 'dashicons dashicons-editor-aligncenter'),
            array('name' => 'alignright', 'className' => 'dashicons dashicons-editor-alignright'),
            array('name' => 'insertmore', 'className' => 'dashicons dashicons-editor-insertmore'),
            array('name' => 'spellcheck', 'className' => 'dashicons dashicons-editor-spellcheck'),
            array('name' => 'expand', 'className' => 'dashicons dashicons-editor-expand'),
            array('name' => 'contract', 'className' => 'dashicons dashicons-editor-contract'),
            array('name' => 'kitchen sink', 'className' => 'dashicons dashicons-editor-kitchensink'),
            array('name' => 'underline', 'className' => 'dashicons dashicons-editor-underline'),
            array('name' => 'justify', 'className' => 'dashicons dashicons-editor-justify'),
            array('name' => 'textcolor', 'className' => 'dashicons dashicons-editor-textcolor'),
            array('name' => 'paste', 'className' => 'dashicons dashicons-editor-paste-word'),
            array('name' => 'paste', 'className' => 'dashicons dashicons-editor-paste-text'),
            array('name' => 'remove formatting', 'className' => 'dashicons dashicons-editor-removeformatting'),
            array('name' => 'video', 'className' => 'dashicons dashicons-editor-video'),
            array('name' => 'custom character', 'className' => 'dashicons dashicons-editor-customchar'),
            array('name' => 'outdent', 'className' => 'dashicons dashicons-editor-outdent'),
            array('name' => 'indent', 'className' => 'dashicons dashicons-editor-indent'),
            array('name' => 'help', 'className' => 'dashicons dashicons-editor-help'),
            array('name' => 'strikethrough', 'className' => 'dashicons dashicons-editor-strikethrough'),
            array('name' => 'unlink', 'className' => 'dashicons dashicons-editor-unlink'),
            array('name' => 'rtl', 'className' => 'dashicons dashicons-editor-rtl'),
            array('name' => 'break', 'className' => 'dashicons dashicons-editor-break'),
            array('name' => 'code', 'className' => 'dashicons dashicons-editor-code'),
            array('name' => 'paragraph', 'className' => 'dashicons dashicons-editor-paragraph'),
            array('name' => 'table', 'className' => 'dashicons dashicons-editor-table'),
            array('name' => 'align left', 'className' => 'dashicons dashicons-align-left'),
            array('name' => 'align right', 'className' => 'dashicons dashicons-align-right'),
            array('name' => 'align center', 'className' => 'dashicons dashicons-align-center'),
            array('name' => 'align none', 'className' => 'dashicons dashicons-align-none'),
            array('name' => 'lock', 'className' => 'dashicons dashicons-lock'),
            array('name' => 'unlock', 'className' => 'dashicons dashicons-unlock'),
            array('name' => 'calendar', 'className' => 'dashicons dashicons-calendar'),
            array('name' => 'calendar', 'className' => 'dashicons dashicons-calendar-alt'),
            array('name' => 'visibility', 'className' => 'dashicons dashicons-visibility'),
            array('name' => 'hidden', 'className' => 'dashicons dashicons-hidden'),
            array('name' => 'post status', 'className' => 'dashicons dashicons-post-status'),
            array('name' => 'edit pencil', 'className' => 'dashicons dashicons-edit'),
            array('name' => 'trash remove delete', 'className' => 'dashicons dashicons-trash'),
            array('name' => 'sticky', 'className' => 'dashicons dashicons-sticky'),
            array('name' => 'external', 'className' => 'dashicons dashicons-external'),
            array('name' => 'arrow-up', 'className' => 'dashicons dashicons-arrow-up'),
            array('name' => 'arrow-down', 'className' => 'dashicons dashicons-arrow-down'),
            array('name' => 'arrow-right', 'className' => 'dashicons dashicons-arrow-right'),
            array('name' => 'arrow-left', 'className' => 'dashicons dashicons-arrow-left'),
            array('name' => 'arrow-up', 'className' => 'dashicons dashicons-arrow-up-alt'),
            array('name' => 'arrow-down', 'className' => 'dashicons dashicons-arrow-down-alt'),
            array('name' => 'arrow-right', 'className' => 'dashicons dashicons-arrow-right-alt'),
            array('name' => 'arrow-left', 'className' => 'dashicons dashicons-arrow-left-alt'),
            array('name' => 'arrow-up', 'className' => 'dashicons dashicons-arrow-up-alt2'),
            array('name' => 'arrow-down', 'className' => 'dashicons dashicons-arrow-down-alt2'),
            array('name' => 'arrow-right', 'className' => 'dashicons dashicons-arrow-right-alt2'),
            array('name' => 'arrow-left', 'className' => 'dashicons dashicons-arrow-left-alt2'),
            array('name' => 'sort', 'className' => 'dashicons dashicons-sort'),
            array('name' => 'left right', 'className' => 'dashicons dashicons-leftright'),
            array('name' => 'randomize shuffle', 'className' => 'dashicons dashicons-randomize'),
            array('name' => 'list view', 'className' => 'dashicons dashicons-list-view'),
            array('name' => 'exerpt view', 'className' => 'dashicons dashicons-exerpt-view'),
            array('name' => 'grid view', 'className' => 'dashicons dashicons-grid-view'),
            array('name' => 'move', 'className' => 'dashicons dashicons-move'),
            array('name' => 'share', 'className' => 'dashicons dashicons-share'),
            array('name' => 'share', 'className' => 'dashicons dashicons-share-alt'),
            array('name' => 'share', 'className' => 'dashicons dashicons-share-alt2'),
            array('name' => 'twitter social', 'className' => 'dashicons dashicons-twitter'),
            array('name' => 'rss', 'className' => 'dashicons dashicons-rss'),
            array('name' => 'email', 'className' => 'dashicons dashicons-email'),
            array('name' => 'email', 'className' => 'dashicons dashicons-email-alt'),
            array('name' => 'facebook social', 'className' => 'dashicons dashicons-facebook'),
            array('name' => 'facebook social', 'className' => 'dashicons dashicons-facebook-alt'),
            array('name' => 'googleplus social', 'className' => 'dashicons dashicons-googleplus'),
            array('name' => 'networking social', 'className' => 'dashicons dashicons-networking'),
            array('name' => 'hammer development', 'className' => 'dashicons dashicons-hammer'),
            array('name' => 'art design', 'className' => 'dashicons dashicons-art'),
            array('name' => 'migrate migration', 'className' => 'dashicons dashicons-migrate'),
            array('name' => 'performance', 'className' => 'dashicons dashicons-performance'),
            array('name' => 'universal access accessibility', 'className' => 'dashicons dashicons-universal-access'),
            array('name' => 'universal access accessibility', 'className' => 'dashicons dashicons-universal-access-alt'),
            array('name' => 'tickets', 'className' => 'dashicons dashicons-tickets'),
            array('name' => 'nametag', 'className' => 'dashicons dashicons-nametag'),
            array('name' => 'clipboard', 'className' => 'dashicons dashicons-clipboard'),
            array('name' => 'heart', 'className' => 'dashicons dashicons-heart'),
            array('name' => 'megaphone', 'className' => 'dashicons dashicons-megaphone'),
            array('name' => 'schedule', 'className' => 'dashicons dashicons-schedule'),
            array('name' => 'wordpress', 'className' => 'dashicons dashicons-wordpress'),
            array('name' => 'wordpress', 'className' => 'dashicons dashicons-wordpress-alt'),
            array('name' => 'press this', 'className' => 'dashicons dashicons-pressthis'),
            array('name' => 'update', 'className' => 'dashicons dashicons-update'),
            array('name' => 'screenoptions', 'className' => 'dashicons dashicons-screenoptions'),
            array('name' => 'info', 'className' => 'dashicons dashicons-info'),
            array('name' => 'cart shopping', 'className' => 'dashicons dashicons-cart'),
            array('name' => 'feedback form', 'className' => 'dashicons dashicons-feedback'),
            array('name' => 'cloud', 'className' => 'dashicons dashicons-cloud'),
            array('name' => 'translation language', 'className' => 'dashicons dashicons-translation'),
            array('name' => 'tag', 'className' => 'dashicons dashicons-tag'),
            array('name' => 'category', 'className' => 'dashicons dashicons-category'),
            array('name' => 'archive', 'className' => 'dashicons dashicons-archive'),
            array('name' => 'tagcloud', 'className' => 'dashicons dashicons-tagcloud'),
            array('name' => 'text', 'className' => 'dashicons dashicons-text'),
            array('name' => 'yes check checkmark', 'className' => 'dashicons dashicons-yes'),
            array('name' => 'no x', 'className' => 'dashicons dashicons-no'),
            array('name' => 'no x', 'className' => 'dashicons dashicons-no-alt'),
            array('name' => 'plus add increase', 'className' => 'dashicons dashicons-plus'),
            array('name' => 'plus add increase', 'className' => 'dashicons dashicons-plus-alt'),
            array('name' => 'minus decrease', 'className' => 'dashicons dashicons-minus'),
            array('name' => 'dismiss', 'className' => 'dashicons dashicons-dismiss'),
            array('name' => 'marker', 'className' => 'dashicons dashicons-marker'),
            array('name' => 'filled star', 'className' => 'dashicons dashicons-star-filled'),
            array('name' => 'half star', 'className' => 'dashicons dashicons-star-half'),
            array('name' => 'empty star', 'className' => 'dashicons dashicons-star-empty'),
            array('name' => 'flag', 'className' => 'dashicons dashicons-flag'),
            array('name' => 'warning', 'className' => 'dashicons dashicons-warning'),
            array('name' => 'location pin', 'className' => 'dashicons dashicons-location'),
            array('name' => 'location', 'className' => 'dashicons dashicons-location-alt'),
            array('name' => 'vault safe', 'className' => 'dashicons dashicons-vault'),
            array('name' => 'shield', 'className' => 'dashicons dashicons-shield'),
            array('name' => 'shield', 'className' => 'dashicons dashicons-shield-alt'),
            array('name' => 'sos help', 'className' => 'dashicons dashicons-sos'),
            array('name' => 'search', 'className' => 'dashicons dashicons-search'),
            array('name' => 'slides', 'className' => 'dashicons dashicons-slides'),
            array('name' => 'analytics', 'className' => 'dashicons dashicons-analytics'),
            array('name' => 'pie chart', 'className' => 'dashicons dashicons-chart-pie'),
            array('name' => 'bar chart', 'className' => 'dashicons dashicons-chart-bar'),
            array('name' => 'line chart', 'className' => 'dashicons dashicons-chart-line'),
            array('name' => 'area chart', 'className' => 'dashicons dashicons-chart-area'),
            array('name' => 'groups', 'className' => 'dashicons dashicons-groups'),
            array('name' => 'businessman', 'className' => 'dashicons dashicons-businessman'),
            array('name' => 'id', 'className' => 'dashicons dashicons-id'),
            array('name' => 'id', 'className' => 'dashicons dashicons-id-alt'),
            array('name' => 'products', 'className' => 'dashicons dashicons-products'),
            array('name' => 'awards', 'className' => 'dashicons dashicons-awards'),
            array('name' => 'forms', 'className' => 'dashicons dashicons-forms'),
            array('name' => 'testimonial', 'className' => 'dashicons dashicons-testimonial'),
            array('name' => 'portfolio', 'className' => 'dashicons dashicons-portfolio'),
            array('name' => 'book', 'className' => 'dashicons dashicons-book'),
            array('name' => 'book', 'className' => 'dashicons dashicons-book-alt'),
            array('name' => 'download', 'className' => 'dashicons dashicons-download'),
            array('name' => 'upload', 'className' => 'dashicons dashicons-upload'),
            array('name' => 'backup', 'className' => 'dashicons dashicons-backup'),
            array('name' => 'clock', 'className' => 'dashicons dashicons-clock'),
            array('name' => 'lightbulb', 'className' => 'dashicons dashicons-lightbulb'),
            array('name' => 'microphone mic', 'className' => 'dashicons dashicons-microphone'),
            array('name' => 'desktop monitor', 'className' => 'dashicons dashicons-desktop'),
            array('name' => 'laptop', 'className' => 'dashicons dashicons-laptop'),
            array('name' => 'tablet ipad', 'className' => 'dashicons dashicons-tablet'),
            array('name' => 'smartphone iphone', 'className' => 'dashicons dashicons-smartphone'),
            array('name' => 'phone', 'className' => 'dashicons dashicons-phone'),
            array('name' => 'index card', 'className' => 'dashicons dashicons-index-card'),
            array('name' => 'carrot food vendor', 'className' => 'dashicons dashicons-carrot'),
            array('name' => 'building', 'className' => 'dashicons dashicons-building'),
            array('name' => 'store', 'className' => 'dashicons dashicons-store'),
            array('name' => 'album', 'className' => 'dashicons dashicons-album'),
            array('name' => 'palm tree', 'className' => 'dashicons dashicons-palmtree'),
            array('name' => 'tickets (alt)', 'className' => 'dashicons dashicons-tickets-alt'),
            array('name' => 'money', 'className' => 'dashicons dashicons-money'),
            array('name' => 'smiley smile', 'className' => 'dashicons dashicons-smiley'),
            array('name' => 'thumbs up', 'className' => 'dashicons dashicons-thumbs-up'),
            array('name' => 'thumbs down', 'className' => 'dashicons dashicons-thumbs-down'),
            array('name' => 'layout', 'className' => 'dashicons dashicons-layout'),
            array('name' => 'paperclip', 'className' => 'dashicons dashicons-paperclip'),
        ),
    );

    return $icons;
}
