<?php

add_filter('reuse_icon_picker', 'userplace_fontawesome', 1, 1);

function userplace_fontawesome($icons)
{
	$icons[] = array(
		'label' => esc_html__('Font Awesome', 'userplace'),
		'value' => 'fa',
		'icons' => array(
			array('name' => 'american-sign-language-interpreting', 'className' => 'fa fa-american-sign-language-interpreting'),
			array('name' => 'asl-interpreting (alias)', 'className' => 'fa fa-asl-interpreting'),
			array('name' => 'assistive-listening-systems', 'className' => 'fa fa-assistive-listening-systems'),
			array('name' => 'audio-description', 'className' => 'fa fa-audio-description'),
			array('name' => 'blind', 'className' => 'fa fa-blind'),
			array('name' => 'braille', 'className' => 'fa fa-braille'),
			array('name' => 'deaf', 'className' => 'fa fa-deaf'),
			array('name' => 'deafness (alias)', 'className' => 'fa fa-deafness'),
			array('name' => 'envira', 'className' => 'fa fa-envira'),
			array('name' => 'fa (alias)', 'className' => 'fa fa-fa'),
			array('name' => 'first-order', 'className' => 'fa fa-first-order'),
			array('name' => 'font-awesome', 'className' => 'fa fa-font-awesome'),
			array('name' => 'gitlab', 'className' => 'fa fa-gitlab'),
			array('name' => 'glide', 'className' => 'fa fa-glide'),
			array('name' => 'glide-g', 'className' => 'fa fa-glide-g'),
			array('name' => 'google-plus-circle (alias)', 'className' => 'fa fa-google-plus-circle'),
			array('name' => 'google-plus-official', 'className' => 'fa fa-google-plus-official'),
			array('name' => 'hard-of-hearing (alias)', 'className' => 'fa fa-hard-of-hearing'),
			array('name' => 'instagram', 'className' => 'fa fa-instagram'),
			array('name' => 'low-vision', 'className' => 'fa fa-low-vision'),
			array('name' => 'pied-piper', 'className' => 'fa fa-pied-piper'),
			array('name' => 'question-circle-o', 'className' => 'fa fa-question-circle-o'),
			array('name' => 'sign-language', 'className' => 'fa fa-sign-language'),
			array('name' => 'signing (alias)', 'className' => 'fa fa-signing'),
			array('name' => 'snapchat', 'className' => 'fa fa-snapchat'),
			array('name' => 'snapchat-ghost', 'className' => 'fa fa-snapchat-ghost'),
			array('name' => 'snapchat-square', 'className' => 'fa fa-snapchat-square'),
			array('name' => 'themeisle', 'className' => 'fa fa-themeisle'),
			array('name' => 'universal-access', 'className' => 'fa fa-universal-access'),
			array('name' => 'viadeo', 'className' => 'fa fa-viadeo'),
			array('name' => 'viadeo-square', 'className' => 'fa fa-viadeo-square'),
			array('name' => 'volume-control-phone', 'className' => 'fa fa-volume-control-phone'),
			array('name' => 'wheelchair-alt', 'className' => 'fa fa-wheelchair-alt'),
			array('name' => 'wpbeginner', 'className' => 'fa fa-wpbeginner'),
			array('name' => 'wpforms', 'className' => 'fa fa-wpforms'),
			array('name' => 'yoast', 'className' => 'fa fa-yoast'),
			array('name' => 'adjust', 'className' => 'fa fa-adjust'),
			array('name' => 'american-sign-language-interpreting', 'className' => 'fa fa-american-sign-language-interpreting'),
			array('name' => 'anchor', 'className' => 'fa fa-anchor'),
			array('name' => 'archive', 'className' => 'fa fa-archive'),
			array('name' => 'area-chart', 'className' => 'fa fa-area-chart'),
			array('name' => 'arrows', 'className' => 'fa fa-arrows'),
			array('name' => 'arrows-h', 'className' => 'fa fa-arrows-h'),
			array('name' => 'arrows-v', 'className' => 'fa fa-arrows-v'),
			array('name' => 'asl-interpreting (alias)', 'className' => 'fa fa-asl-interpreting'),
			array('name' => 'assistive-listening-systems', 'className' => 'fa fa-assistive-listening-systems'),
			array('name' => 'asterisk', 'className' => 'fa fa-asterisk'),
			array('name' => 'at', 'className' => 'fa fa-at'),
			array('name' => 'audio-description', 'className' => 'fa fa-audio-description'),
			array('name' => 'automobile (alias)', 'className' => 'fa fa-automobile'),
			array('name' => 'balance-scale', 'className' => 'fa fa-balance-scale'),
			array('name' => 'ban', 'className' => 'fa fa-ban'),
			array('name' => 'bank (alias)', 'className' => 'fa fa-bank'),
			array('name' => 'bar-chart', 'className' => 'fa fa-bar-chart'),
			array('name' => 'bar-chart-o (alias)', 'className' => 'fa fa-bar-chart-o'),
			array('name' => 'barcode', 'className' => 'fa fa-barcode'),
			array('name' => 'bars', 'className' => 'fa fa-bars'),
			array('name' => 'battery-0 (alias)', 'className' => 'fa fa-battery-0'),
			array('name' => 'battery-1 (alias)', 'className' => 'fa fa-battery-1'),
			array('name' => 'battery-2 (alias)', 'className' => 'fa fa-battery-2'),
			array('name' => 'battery-3 (alias)', 'className' => 'fa fa-battery-3'),
			array('name' => 'battery-4 (alias)', 'className' => 'fa fa-battery-4'),
			array('name' => 'battery-empty', 'className' => 'fa fa-battery-empty'),
			array('name' => 'battery-full', 'className' => 'fa fa-battery-full'),
			array('name' => 'battery-half', 'className' => 'fa fa-battery-half'),
			array('name' => 'battery-quarter', 'className' => 'fa fa-battery-quarter'),
			array('name' => 'battery-three-quarters', 'className' => 'fa fa-battery-three-quarters'),
			array('name' => 'bed', 'className' => 'fa fa-bed'),
			array('name' => 'beer', 'className' => 'fa fa-beer'),
			array('name' => 'bell', 'className' => 'fa fa-bell'),
			array('name' => 'bell-o', 'className' => 'fa fa-bell-o'),
			array('name' => 'bell-slash', 'className' => 'fa fa-bell-slash'),
			array('name' => 'bell-slash-o', 'className' => 'fa fa-bell-slash-o'),
			array('name' => 'bicycle', 'className' => 'fa fa-bicycle'),
			array('name' => 'binoculars', 'className' => 'fa fa-binoculars'),
			array('name' => 'birthday-cake', 'className' => 'fa fa-birthday-cake'),
			array('name' => 'blind', 'className' => 'fa fa-blind'),
			array('name' => 'bluetooth', 'className' => 'fa fa-bluetooth'),
			array('name' => 'bluetooth-b', 'className' => 'fa fa-bluetooth-b'),
			array('name' => 'bolt', 'className' => 'fa fa-bolt'),
			array('name' => 'bomb', 'className' => 'fa fa-bomb'),
			array('name' => 'book', 'className' => 'fa fa-book'),
			array('name' => 'bookmark', 'className' => 'fa fa-bookmark'),
			array('name' => 'bookmark-o', 'className' => 'fa fa-bookmark-o'),
			array('name' => 'braille', 'className' => 'fa fa-braille'),
			array('name' => 'briefcase', 'className' => 'fa fa-briefcase'),
			array('name' => 'bug', 'className' => 'fa fa-bug'),
			array('name' => 'building', 'className' => 'fa fa-building'),
			array('name' => 'building-o', 'className' => 'fa fa-building-o'),
			array('name' => 'bullhorn', 'className' => 'fa fa-bullhorn'),
			array('name' => 'bullseye', 'className' => 'fa fa-bullseye'),
			array('name' => 'bus', 'className' => 'fa fa-bus'),
			array('name' => 'cab (alias)', 'className' => 'fa fa-cab'),
			array('name' => 'calculator', 'className' => 'fa fa-calculator'),
			array('name' => 'calendar', 'className' => 'fa fa-calendar'),
			array('name' => 'calendar-check-o', 'className' => 'fa fa-calendar-check-o'),
			array('name' => 'calendar-minus-o', 'className' => 'fa fa-calendar-minus-o'),
			array('name' => 'calendar-o', 'className' => 'fa fa-calendar-o'),
			array('name' => 'calendar-plus-o', 'className' => 'fa fa-calendar-plus-o'),
			array('name' => 'calendar-times-o', 'className' => 'fa fa-calendar-times-o'),
			array('name' => 'camera', 'className' => 'fa fa-camera'),
			array('name' => 'camera-retro', 'className' => 'fa fa-camera-retro'),
			array('name' => 'car', 'className' => 'fa fa-car'),
			array('name' => 'caret-square-o-down', 'className' => 'fa fa-caret-square-o-down'),
			array('name' => 'caret-square-o-left', 'className' => 'fa fa-caret-square-o-left'),
			array('name' => 'caret-square-o-right', 'className' => 'fa fa-caret-square-o-right'),
			array('name' => 'caret-square-o-up', 'className' => 'fa fa-caret-square-o-up'),
			array('name' => 'cart-arrow-down', 'className' => 'fa fa-cart-arrow-down'),
			array('name' => 'cart-plus', 'className' => 'fa fa-cart-plus'),
			array('name' => 'cc', 'className' => 'fa fa-cc'),
			array('name' => 'certificate', 'className' => 'fa fa-certificate'),
			array('name' => 'check', 'className' => 'fa fa-check'),
			array('name' => 'check-circle', 'className' => 'fa fa-check-circle'),
			array('name' => 'check-circle-o', 'className' => 'fa fa-check-circle-o'),
			array('name' => 'check-square', 'className' => 'fa fa-check-square'),
			array('name' => 'check-square-o', 'className' => 'fa fa-check-square-o'),
			array('name' => 'child', 'className' => 'fa fa-child'),
			array('name' => 'circle', 'className' => 'fa fa-circle'),
			array('name' => 'circle-o', 'className' => 'fa fa-circle-o'),
			array('name' => 'circle-o-notch', 'className' => 'fa fa-circle-o-notch'),
			array('name' => 'circle-thin', 'className' => 'fa fa-circle-thin'),
			array('name' => 'clock-o', 'className' => 'fa fa-clock-o'),
			array('name' => 'clone', 'className' => 'fa fa-clone'),
			array('name' => 'close (alias)', 'className' => 'fa fa-close'),
			array('name' => 'cloud', 'className' => 'fa fa-cloud'),
			array('name' => 'cloud-download', 'className' => 'fa fa-cloud-download'),
			array('name' => 'cloud-upload', 'className' => 'fa fa-cloud-upload'),
			array('name' => 'code', 'className' => 'fa fa-code'),
			array('name' => 'code-fork', 'className' => 'fa fa-code-fork'),
			array('name' => 'coffee', 'className' => 'fa fa-coffee'),
			array('name' => 'cog', 'className' => 'fa fa-cog'),
			array('name' => 'cogs', 'className' => 'fa fa-cogs'),
			array('name' => 'comment', 'className' => 'fa fa-comment'),
			array('name' => 'comment-o', 'className' => 'fa fa-comment-o'),
			array('name' => 'commenting', 'className' => 'fa fa-commenting'),
			array('name' => 'commenting-o', 'className' => 'fa fa-commenting-o'),
			array('name' => 'comments', 'className' => 'fa fa-comments'),
			array('name' => 'comments-o', 'className' => 'fa fa-comments-o'),
			array('name' => 'compass', 'className' => 'fa fa-compass'),
			array('name' => 'copyright', 'className' => 'fa fa-copyright'),
			array('name' => 'creative-commons', 'className' => 'fa fa-creative-commons'),
			array('name' => 'credit-card', 'className' => 'fa fa-credit-card'),
			array('name' => 'credit-card-alt', 'className' => 'fa fa-credit-card-alt'),
			array('name' => 'crop', 'className' => 'fa fa-crop'),
			array('name' => 'crosshairs', 'className' => 'fa fa-crosshairs'),
			array('name' => 'cube', 'className' => 'fa fa-cube'),
			array('name' => 'cubes', 'className' => 'fa fa-cubes'),
			array('name' => 'cutlery', 'className' => 'fa fa-cutlery'),
			array('name' => 'dashboard (alias)', 'className' => 'fa fa-dashboard'),
			array('name' => 'database', 'className' => 'fa fa-database'),
			array('name' => 'deaf', 'className' => 'fa fa-deaf'),
			array('name' => 'deafness (alias)', 'className' => 'fa fa-deafness'),
			array('name' => 'desktop', 'className' => 'fa fa-desktop'),
			array('name' => 'diamond', 'className' => 'fa fa-diamond'),
			array('name' => 'dot-circle-o', 'className' => 'fa fa-dot-circle-o'),
			array('name' => 'download', 'className' => 'fa fa-download'),
			array('name' => 'edit (alias)', 'className' => 'fa fa-edit'),
			array('name' => 'ellipsis-h', 'className' => 'fa fa-ellipsis-h'),
			array('name' => 'ellipsis-v', 'className' => 'fa fa-ellipsis-v'),
			array('name' => 'envelope', 'className' => 'fa fa-envelope'),
			array('name' => 'envelope-o', 'className' => 'fa fa-envelope-o'),
			array('name' => 'envelope-square', 'className' => 'fa fa-envelope-square'),
			array('name' => 'eraser', 'className' => 'fa fa-eraser'),
			array('name' => 'exchange', 'className' => 'fa fa-exchange'),
			array('name' => 'exclamation', 'className' => 'fa fa-exclamation'),
			array('name' => 'exclamation-circle', 'className' => 'fa fa-exclamation-circle'),
			array('name' => 'exclamation-triangle', 'className' => 'fa fa-exclamation-triangle'),
			array('name' => 'external-link', 'className' => 'fa fa-external-link'),
			array('name' => 'external-link-square', 'className' => 'fa fa-external-link-square'),
			array('name' => 'eye', 'className' => 'fa fa-eye'),
			array('name' => 'eye-slash', 'className' => 'fa fa-eye-slash'),
			array('name' => 'eyedropper', 'className' => 'fa fa-eyedropper'),
			array('name' => 'fax', 'className' => 'fa fa-fax'),
			array('name' => 'feed (alias)', 'className' => 'fa fa-feed'),
			array('name' => 'female', 'className' => 'fa fa-female'),
			array('name' => 'fighter-jet', 'className' => 'fa fa-fighter-jet'),
			array('name' => 'file-archive-o', 'className' => 'fa fa-file-archive-o'),
			array('name' => 'file-audio-o', 'className' => 'fa fa-file-audio-o'),
			array('name' => 'file-code-o', 'className' => 'fa fa-file-code-o'),
			array('name' => 'file-excel-o', 'className' => 'fa fa-file-excel-o'),
			array('name' => 'file-image-o', 'className' => 'fa fa-file-image-o'),
			array('name' => 'file-movie-o (alias)', 'className' => 'fa fa-file-movie-o'),
			array('name' => 'file-pdf-o', 'className' => 'fa fa-file-pdf-o'),
			array('name' => 'file-photo-o (alias)', 'className' => 'fa fa-file-photo-o'),
			array('name' => 'file-picture-o (alias)', 'className' => 'fa fa-file-picture-o'),
			array('name' => 'file-powerpoint-o', 'className' => 'fa fa-file-powerpoint-o'),
			array('name' => 'file-sound-o (alias)', 'className' => 'fa fa-file-sound-o'),
			array('name' => 'file-video-o', 'className' => 'fa fa-file-video-o'),
			array('name' => 'file-word-o', 'className' => 'fa fa-file-word-o'),
			array('name' => 'file-zip-o (alias)', 'className' => 'fa fa-file-zip-o'),
			array('name' => 'film', 'className' => 'fa fa-film'),
			array('name' => 'filter', 'className' => 'fa fa-filter'),
			array('name' => 'fire', 'className' => 'fa fa-fire'),
			array('name' => 'fire-extinguisher', 'className' => 'fa fa-fire-extinguisher'),
			array('name' => 'flag', 'className' => 'fa fa-flag'),
			array('name' => 'flag-checkered', 'className' => 'fa fa-flag-checkered'),
			array('name' => 'flag-o', 'className' => 'fa fa-flag-o'),
			array('name' => 'flash (alias)', 'className' => 'fa fa-flash'),
			array('name' => 'flask', 'className' => 'fa fa-flask'),
			array('name' => 'folder', 'className' => 'fa fa-folder'),
			array('name' => 'folder-o', 'className' => 'fa fa-folder-o'),
			array('name' => 'folder-open', 'className' => 'fa fa-folder-open'),
			array('name' => 'folder-open-o', 'className' => 'fa fa-folder-open-o'),
			array('name' => 'frown-o', 'className' => 'fa fa-frown-o'),
			array('name' => 'futbol-o', 'className' => 'fa fa-futbol-o'),
			array('name' => 'gamepad', 'className' => 'fa fa-gamepad'),
			array('name' => 'gavel', 'className' => 'fa fa-gavel'),
			array('name' => 'gear (alias)', 'className' => 'fa fa-gear'),
			array('name' => 'gears (alias)', 'className' => 'fa fa-gears'),
			array('name' => 'gift', 'className' => 'fa fa-gift'),
			array('name' => 'glass', 'className' => 'fa fa-glass'),
			array('name' => 'globe', 'className' => 'fa fa-globe'),
			array('name' => 'graduation-cap', 'className' => 'fa fa-graduation-cap'),
			array('name' => 'group (alias)', 'className' => 'fa fa-group'),
			array('name' => 'hand-grab-o (alias)', 'className' => 'fa fa-hand-grab-o'),
			array('name' => 'hand-lizard-o', 'className' => 'fa fa-hand-lizard-o'),
			array('name' => 'hand-paper-o', 'className' => 'fa fa-hand-paper-o'),
			array('name' => 'hand-peace-o', 'className' => 'fa fa-hand-peace-o'),
			array('name' => 'hand-pointer-o', 'className' => 'fa fa-hand-pointer-o'),
			array('name' => 'hand-rock-o', 'className' => 'fa fa-hand-rock-o'),
			array('name' => 'hand-scissors-o', 'className' => 'fa fa-hand-scissors-o'),
			array('name' => 'hand-spock-o', 'className' => 'fa fa-hand-spock-o'),
			array('name' => 'hand-stop-o (alias)', 'className' => 'fa fa-hand-stop-o'),
			array('name' => 'hard-of-hearing (alias)', 'className' => 'fa fa-hard-of-hearing'),
			array('name' => 'hashtag', 'className' => 'fa fa-hashtag'),
			array('name' => 'hdd-o', 'className' => 'fa fa-hdd-o'),
			array('name' => 'headphones', 'className' => 'fa fa-headphones'),
			array('name' => 'heart', 'className' => 'fa fa-heart'),
			array('name' => 'heart-o', 'className' => 'fa fa-heart-o'),
			array('name' => 'heartbeat', 'className' => 'fa fa-heartbeat'),
			array('name' => 'history', 'className' => 'fa fa-history'),
			array('name' => 'home', 'className' => 'fa fa-home'),
			array('name' => 'hotel (alias)', 'className' => 'fa fa-hotel'),
			array('name' => 'hourglass', 'className' => 'fa fa-hourglass'),
			array('name' => 'hourglass-1 (alias)', 'className' => 'fa fa-hourglass-1'),
			array('name' => 'hourglass-2 (alias)', 'className' => 'fa fa-hourglass-2'),
			array('name' => 'hourglass-3 (alias)', 'className' => 'fa fa-hourglass-3'),
			array('name' => 'hourglass-end', 'className' => 'fa fa-hourglass-end'),
			array('name' => 'hourglass-half', 'className' => 'fa fa-hourglass-half'),
			array('name' => 'hourglass-o', 'className' => 'fa fa-hourglass-o'),
			array('name' => 'hourglass-start', 'className' => 'fa fa-hourglass-start'),
			array('name' => 'i-cursor', 'className' => 'fa fa-i-cursor'),
			array('name' => 'image (alias)', 'className' => 'fa fa-image'),
			array('name' => 'inbox', 'className' => 'fa fa-inbox'),
			array('name' => 'industry', 'className' => 'fa fa-industry'),
			array('name' => 'info', 'className' => 'fa fa-info'),
			array('name' => 'info-circle', 'className' => 'fa fa-info-circle'),
			array('name' => 'institution (alias)', 'className' => 'fa fa-institution'),
			array('name' => 'key', 'className' => 'fa fa-key'),
			array('name' => 'keyboard-o', 'className' => 'fa fa-keyboard-o'),
			array('name' => 'language', 'className' => 'fa fa-language'),
			array('name' => 'laptop', 'className' => 'fa fa-laptop'),
			array('name' => 'leaf', 'className' => 'fa fa-leaf'),
			array('name' => 'legal (alias)', 'className' => 'fa fa-legal'),
			array('name' => 'lemon-o', 'className' => 'fa fa-lemon-o'),
			array('name' => 'level-down', 'className' => 'fa fa-level-down'),
			array('name' => 'level-up', 'className' => 'fa fa-level-up'),
			array('name' => 'life-bouy (alias)', 'className' => 'fa fa-life-bouy'),
			array('name' => 'life-buoy (alias)', 'className' => 'fa fa-life-buoy'),
			array('name' => 'life-ring', 'className' => 'fa fa-life-ring'),
			array('name' => 'life-saver (alias)', 'className' => 'fa fa-life-saver'),
			array('name' => 'lightbulb-o', 'className' => 'fa fa-lightbulb-o'),
			array('name' => 'line-chart', 'className' => 'fa fa-line-chart'),
			array('name' => 'location-arrow', 'className' => 'fa fa-location-arrow'),
			array('name' => 'lock', 'className' => 'fa fa-lock'),
			array('name' => 'low-vision', 'className' => 'fa fa-low-vision'),
			array('name' => 'magic', 'className' => 'fa fa-magic'),
			array('name' => 'magnet', 'className' => 'fa fa-magnet'),
			array('name' => 'mail-forward (alias)', 'className' => 'fa fa-mail-forward'),
			array('name' => 'mail-reply (alias)', 'className' => 'fa fa-mail-reply'),
			array('name' => 'mail-reply-all (alias)', 'className' => 'fa fa-mail-reply-all'),
			array('name' => 'male', 'className' => 'fa fa-male'),
			array('name' => 'map', 'className' => 'fa fa-map'),
			array('name' => 'map-marker', 'className' => 'fa fa-map-marker'),
			array('name' => 'map-o', 'className' => 'fa fa-map-o'),
			array('name' => 'map-pin', 'className' => 'fa fa-map-pin'),
			array('name' => 'map-signs', 'className' => 'fa fa-map-signs'),
			array('name' => 'meh-o', 'className' => 'fa fa-meh-o'),
			array('name' => 'microphone', 'className' => 'fa fa-microphone'),
			array('name' => 'microphone-slash', 'className' => 'fa fa-microphone-slash'),
			array('name' => 'minus', 'className' => 'fa fa-minus'),
			array('name' => 'minus-circle', 'className' => 'fa fa-minus-circle'),
			array('name' => 'minus-square', 'className' => 'fa fa-minus-square'),
			array('name' => 'minus-square-o', 'className' => 'fa fa-minus-square-o'),
			array('name' => 'mobile', 'className' => 'fa fa-mobile'),
			array('name' => 'mobile-phone (alias)', 'className' => 'fa fa-mobile-phone'),
			array('name' => 'money', 'className' => 'fa fa-money'),
			array('name' => 'moon-o', 'className' => 'fa fa-moon-o'),
			array('name' => 'mortar-board (alias)', 'className' => 'fa fa-mortar-board'),
			array('name' => 'motorcycle', 'className' => 'fa fa-motorcycle'),
			array('name' => 'mouse-pointer', 'className' => 'fa fa-mouse-pointer'),
			array('name' => 'music', 'className' => 'fa fa-music'),
			array('name' => 'navicon (alias)', 'className' => 'fa fa-navicon'),
			array('name' => 'newspaper-o', 'className' => 'fa fa-newspaper-o'),
			array('name' => 'object-group', 'className' => 'fa fa-object-group'),
			array('name' => 'object-ungroup', 'className' => 'fa fa-object-ungroup'),
			array('name' => 'paint-brush', 'className' => 'fa fa-paint-brush'),
			array('name' => 'paper-plane', 'className' => 'fa fa-paper-plane'),
			array('name' => 'paper-plane-o', 'className' => 'fa fa-paper-plane-o'),
			array('name' => 'paw', 'className' => 'fa fa-paw'),
			array('name' => 'pencil', 'className' => 'fa fa-pencil'),
			array('name' => 'pencil-square', 'className' => 'fa fa-pencil-square'),
			array('name' => 'pencil-square-o', 'className' => 'fa fa-pencil-square-o'),
			array('name' => 'percent', 'className' => 'fa fa-percent'),
			array('name' => 'phone', 'className' => 'fa fa-phone'),
			array('name' => 'phone-square', 'className' => 'fa fa-phone-square'),
			array('name' => 'photo (alias)', 'className' => 'fa fa-photo'),
			array('name' => 'picture-o', 'className' => 'fa fa-picture-o'),
			array('name' => 'pie-chart', 'className' => 'fa fa-pie-chart'),
			array('name' => 'plane', 'className' => 'fa fa-plane'),
			array('name' => 'plug', 'className' => 'fa fa-plug'),
			array('name' => 'plus', 'className' => 'fa fa-plus'),
			array('name' => 'plus-circle', 'className' => 'fa fa-plus-circle'),
			array('name' => 'plus-square', 'className' => 'fa fa-plus-square'),
			array('name' => 'plus-square-o', 'className' => 'fa fa-plus-square-o'),
			array('name' => 'power-off', 'className' => 'fa fa-power-off'),
			array('name' => 'print', 'className' => 'fa fa-print'),
			array('name' => 'puzzle-piece', 'className' => 'fa fa-puzzle-piece'),
			array('name' => 'qrcode', 'className' => 'fa fa-qrcode'),
			array('name' => 'question', 'className' => 'fa fa-question'),
			array('name' => 'question-circle', 'className' => 'fa fa-question-circle'),
			array('name' => 'question-circle-o', 'className' => 'fa fa-question-circle-o'),
			array('name' => 'quote-left', 'className' => 'fa fa-quote-left'),
			array('name' => 'quote-right', 'className' => 'fa fa-quote-right'),
			array('name' => 'random', 'className' => 'fa fa-random'),
			array('name' => 'recycle', 'className' => 'fa fa-recycle'),
			array('name' => 'refresh', 'className' => 'fa fa-refresh'),
			array('name' => 'registered', 'className' => 'fa fa-registered'),
			array('name' => 'remove (alias)', 'className' => 'fa fa-remove'),
			array('name' => 'reorder (alias)', 'className' => 'fa fa-reorder'),
			array('name' => 'reply', 'className' => 'fa fa-reply'),
			array('name' => 'reply-all', 'className' => 'fa fa-reply-all'),
			array('name' => 'retweet', 'className' => 'fa fa-retweet'),
			array('name' => 'road', 'className' => 'fa fa-road'),
			array('name' => 'rocket', 'className' => 'fa fa-rocket'),
			array('name' => 'rss', 'className' => 'fa fa-rss'),
			array('name' => 'rss-square', 'className' => 'fa fa-rss-square'),
			array('name' => 'search', 'className' => 'fa fa-search'),
			array('name' => 'search-minus', 'className' => 'fa fa-search-minus'),
			array('name' => 'search-plus', 'className' => 'fa fa-search-plus'),
			array('name' => 'send (alias)', 'className' => 'fa fa-send'),
			array('name' => 'send-o (alias)', 'className' => 'fa fa-send-o'),
			array('name' => 'server', 'className' => 'fa fa-server'),
			array('name' => 'share', 'className' => 'fa fa-share'),
			array('name' => 'share-alt', 'className' => 'fa fa-share-alt'),
			array('name' => 'share-alt-square', 'className' => 'fa fa-share-alt-square'),
			array('name' => 'share-square', 'className' => 'fa fa-share-square'),
			array('name' => 'share-square-o', 'className' => 'fa fa-share-square-o'),
			array('name' => 'shield', 'className' => 'fa fa-shield'),
			array('name' => 'ship', 'className' => 'fa fa-ship'),
			array('name' => 'shopping-bag', 'className' => 'fa fa-shopping-bag'),
			array('name' => 'shopping-basket', 'className' => 'fa fa-shopping-basket'),
			array('name' => 'shopping-cart', 'className' => 'fa fa-shopping-cart'),
			array('name' => 'sign-in', 'className' => 'fa fa-sign-in'),
			array('name' => 'sign-language', 'className' => 'fa fa-sign-language'),
			array('name' => 'sign-out', 'className' => 'fa fa-sign-out'),
			array('name' => 'signal', 'className' => 'fa fa-signal'),
			array('name' => 'signing (alias)', 'className' => 'fa fa-signing'),
			array('name' => 'sitemap', 'className' => 'fa fa-sitemap'),
			array('name' => 'sliders', 'className' => 'fa fa-sliders'),
			array('name' => 'smile-o', 'className' => 'fa fa-smile-o'),
			array('name' => 'soccer-ball-o (alias)', 'className' => 'fa fa-soccer-ball-o'),
			array('name' => 'sort', 'className' => 'fa fa-sort'),
			array('name' => 'sort-alpha-asc', 'className' => 'fa fa-sort-alpha-asc'),
			array('name' => 'sort-alpha-desc', 'className' => 'fa fa-sort-alpha-desc'),
			array('name' => 'sort-amount-asc', 'className' => 'fa fa-sort-amount-asc'),
			array('name' => 'sort-amount-desc', 'className' => 'fa fa-sort-amount-desc'),
			array('name' => 'sort-asc', 'className' => 'fa fa-sort-asc'),
			array('name' => 'sort-desc', 'className' => 'fa fa-sort-desc'),
			array('name' => 'sort-down (alias)', 'className' => 'fa fa-sort-down'),
			array('name' => 'sort-numeric-asc', 'className' => 'fa fa-sort-numeric-asc'),
			array('name' => 'sort-numeric-desc', 'className' => 'fa fa-sort-numeric-desc'),
			array('name' => 'sort-up (alias)', 'className' => 'fa fa-sort-up'),
			array('name' => 'space-shuttle', 'className' => 'fa fa-space-shuttle'),
			array('name' => 'spinner', 'className' => 'fa fa-spinner'),
			array('name' => 'spoon', 'className' => 'fa fa-spoon'),
			array('name' => 'square', 'className' => 'fa fa-square'),
			array('name' => 'square-o', 'className' => 'fa fa-square-o'),
			array('name' => 'star', 'className' => 'fa fa-star'),
			array('name' => 'star-half', 'className' => 'fa fa-star-half'),
			array('name' => 'star-half-empty (alias)', 'className' => 'fa fa-star-half-empty'),
			array('name' => 'star-half-full (alias)', 'className' => 'fa fa-star-half-full'),
			array('name' => 'star-half-o', 'className' => 'fa fa-star-half-o'),
			array('name' => 'star-o', 'className' => 'fa fa-star-o'),
			array('name' => 'sticky-note', 'className' => 'fa fa-sticky-note'),
			array('name' => 'sticky-note-o', 'className' => 'fa fa-sticky-note-o'),
			array('name' => 'street-view', 'className' => 'fa fa-street-view'),
			array('name' => 'suitcase', 'className' => 'fa fa-suitcase'),
			array('name' => 'sun-o', 'className' => 'fa fa-sun-o'),
			array('name' => 'support (alias)', 'className' => 'fa fa-support'),
			array('name' => 'tablet', 'className' => 'fa fa-tablet'),
			array('name' => 'tachometer', 'className' => 'fa fa-tachometer'),
			array('name' => 'tag', 'className' => 'fa fa-tag'),
			array('name' => 'tags', 'className' => 'fa fa-tags'),
			array('name' => 'tasks', 'className' => 'fa fa-tasks'),
			array('name' => 'taxi', 'className' => 'fa fa-taxi'),
			array('name' => 'television', 'className' => 'fa fa-television'),
			array('name' => 'terminal', 'className' => 'fa fa-terminal'),
			array('name' => 'thumb-tack', 'className' => 'fa fa-thumb-tack'),
			array('name' => 'thumbs-down', 'className' => 'fa fa-thumbs-down'),
			array('name' => 'thumbs-o-down', 'className' => 'fa fa-thumbs-o-down'),
			array('name' => 'thumbs-o-up', 'className' => 'fa fa-thumbs-o-up'),
			array('name' => 'thumbs-up', 'className' => 'fa fa-thumbs-up'),
			array('name' => 'ticket', 'className' => 'fa fa-ticket'),
			array('name' => 'times', 'className' => 'fa fa-times'),
			array('name' => 'times-circle', 'className' => 'fa fa-times-circle'),
			array('name' => 'times-circle-o', 'className' => 'fa fa-times-circle-o'),
			array('name' => 'tint', 'className' => 'fa fa-tint'),
			array('name' => 'toggle-down (alias)', 'className' => 'fa fa-toggle-down'),
			array('name' => 'toggle-left (alias)', 'className' => 'fa fa-toggle-left'),
			array('name' => 'toggle-off', 'className' => 'fa fa-toggle-off'),
			array('name' => 'toggle-on', 'className' => 'fa fa-toggle-on'),
			array('name' => 'toggle-right (alias)', 'className' => 'fa fa-toggle-right'),
			array('name' => 'toggle-up (alias)', 'className' => 'fa fa-toggle-up'),
			array('name' => 'trademark', 'className' => 'fa fa-trademark'),
			array('name' => 'trash', 'className' => 'fa fa-trash'),
			array('name' => 'trash-o', 'className' => 'fa fa-trash-o'),
			array('name' => 'tree', 'className' => 'fa fa-tree'),
			array('name' => 'trophy', 'className' => 'fa fa-trophy'),
			array('name' => 'truck', 'className' => 'fa fa-truck'),
			array('name' => 'tty', 'className' => 'fa fa-tty'),
			array('name' => 'tv (alias)', 'className' => 'fa fa-tv'),
			array('name' => 'umbrella', 'className' => 'fa fa-umbrella'),
			array('name' => 'universal-access', 'className' => 'fa fa-universal-access'),
			array('name' => 'university', 'className' => 'fa fa-university'),
			array('name' => 'unlock', 'className' => 'fa fa-unlock'),
			array('name' => 'unlock-alt', 'className' => 'fa fa-unlock-alt'),
			array('name' => 'unsorted (alias)', 'className' => 'fa fa-unsorted'),
			array('name' => 'upload', 'className' => 'fa fa-upload'),
			array('name' => 'user', 'className' => 'fa fa-user'),
			array('name' => 'user-plus', 'className' => 'fa fa-user-plus'),
			array('name' => 'user-secret', 'className' => 'fa fa-user-secret'),
			array('name' => 'user-times', 'className' => 'fa fa-user-times'),
			array('name' => 'users', 'className' => 'fa fa-users'),
			array('name' => 'video-camera', 'className' => 'fa fa-video-camera'),
			array('name' => 'volume-control-phone', 'className' => 'fa fa-volume-control-phone'),
			array('name' => 'volume-down', 'className' => 'fa fa-volume-down'),
			array('name' => 'volume-off', 'className' => 'fa fa-volume-off'),
			array('name' => 'volume-up', 'className' => 'fa fa-volume-up'),
			array('name' => 'warning (alias)', 'className' => 'fa fa-warning'),
			array('name' => 'wheelchair', 'className' => 'fa fa-wheelchair'),
			array('name' => 'wheelchair-alt', 'className' => 'fa fa-wheelchair-alt'),
			array('name' => 'wifi', 'className' => 'fa fa-wifi'),
			array('name' => 'wrench', 'className' => 'fa fa-wrench'),
			array('name' => 'american-sign-language-interpreting', 'className' => 'fa fa-american-sign-language-interpreting'),
			array('name' => 'asl-interpreting (alias)', 'className' => 'fa fa-asl-interpreting'),
			array('name' => 'assistive-listening-systems', 'className' => 'fa fa-assistive-listening-systems'),
			array('name' => 'audio-description', 'className' => 'fa fa-audio-description'),
			array('name' => 'blind', 'className' => 'fa fa-blind'),
			array('name' => 'braille', 'className' => 'fa fa-braille'),
			array('name' => 'cc', 'className' => 'fa fa-cc'),
			array('name' => 'deaf', 'className' => 'fa fa-deaf'),
			array('name' => 'deafness (alias)', 'className' => 'fa fa-deafness'),
			array('name' => 'hard-of-hearing (alias)', 'className' => 'fa fa-hard-of-hearing'),
			array('name' => 'low-vision', 'className' => 'fa fa-low-vision'),
			array('name' => 'question-circle-o', 'className' => 'fa fa-question-circle-o'),
			array('name' => 'sign-language', 'className' => 'fa fa-sign-language'),
			array('name' => 'signing (alias)', 'className' => 'fa fa-signing'),
			array('name' => 'tty', 'className' => 'fa fa-tty'),
			array('name' => 'universal-access', 'className' => 'fa fa-universal-access'),
			array('name' => 'volume-control-phone', 'className' => 'fa fa-volume-control-phone'),
			array('name' => 'wheelchair', 'className' => 'fa fa-wheelchair'),
			array('name' => 'wheelchair-alt', 'className' => 'fa fa-wheelchair-alt'),
			array('name' => 'hand-grab-o (alias)', 'className' => 'fa fa-hand-grab-o'),
			array('name' => 'hand-lizard-o', 'className' => 'fa fa-hand-lizard-o'),
			array('name' => 'hand-o-down', 'className' => 'fa fa-hand-o-down'),
			array('name' => 'hand-o-left', 'className' => 'fa fa-hand-o-left'),
			array('name' => 'hand-o-right', 'className' => 'fa fa-hand-o-right'),
			array('name' => 'hand-o-up', 'className' => 'fa fa-hand-o-up'),
			array('name' => 'hand-paper-o', 'className' => 'fa fa-hand-paper-o'),
			array('name' => 'hand-peace-o', 'className' => 'fa fa-hand-peace-o'),
			array('name' => 'hand-pointer-o', 'className' => 'fa fa-hand-pointer-o'),
			array('name' => 'hand-rock-o', 'className' => 'fa fa-hand-rock-o'),
			array('name' => 'hand-scissors-o', 'className' => 'fa fa-hand-scissors-o'),
			array('name' => 'hand-spock-o', 'className' => 'fa fa-hand-spock-o'),
			array('name' => 'hand-stop-o (alias)', 'className' => 'fa fa-hand-stop-o'),
			array('name' => 'thumbs-down', 'className' => 'fa fa-thumbs-down'),
			array('name' => 'thumbs-o-down', 'className' => 'fa fa-thumbs-o-down'),
			array('name' => 'thumbs-o-up', 'className' => 'fa fa-thumbs-o-up'),
			array('name' => 'thumbs-up', 'className' => 'fa fa-thumbs-up'),
			array('name' => 'ambulance', 'className' => 'fa fa-ambulance'),
			array('name' => 'automobile (alias)', 'className' => 'fa fa-automobile'),
			array('name' => 'bicycle', 'className' => 'fa fa-bicycle'),
			array('name' => 'bus', 'className' => 'fa fa-bus'),
			array('name' => 'cab (alias)', 'className' => 'fa fa-cab'),
			array('name' => 'car', 'className' => 'fa fa-car'),
			array('name' => 'fighter-jet', 'className' => 'fa fa-fighter-jet'),
			array('name' => 'motorcycle', 'className' => 'fa fa-motorcycle'),
			array('name' => 'plane', 'className' => 'fa fa-plane'),
			array('name' => 'rocket', 'className' => 'fa fa-rocket'),
			array('name' => 'ship', 'className' => 'fa fa-ship'),
			array('name' => 'space-shuttle', 'className' => 'fa fa-space-shuttle'),
			array('name' => 'subway', 'className' => 'fa fa-subway'),
			array('name' => 'taxi', 'className' => 'fa fa-taxi'),
			array('name' => 'train', 'className' => 'fa fa-train'),
			array('name' => 'truck', 'className' => 'fa fa-truck'),
			array('name' => 'wheelchair', 'className' => 'fa fa-wheelchair'),
			array('name' => 'wheelchair-alt', 'className' => 'fa fa-wheelchair-alt'),
			array('name' => 'genderless', 'className' => 'fa fa-genderless'),
			array('name' => 'intersex (alias)', 'className' => 'fa fa-intersex'),
			array('name' => 'mars', 'className' => 'fa fa-mars'),
			array('name' => 'mars-double', 'className' => 'fa fa-mars-double'),
			array('name' => 'mars-stroke', 'className' => 'fa fa-mars-stroke'),
			array('name' => 'mars-stroke-h', 'className' => 'fa fa-mars-stroke-h'),
			array('name' => 'mars-stroke-v', 'className' => 'fa fa-mars-stroke-v'),
			array('name' => 'mercury', 'className' => 'fa fa-mercury'),
			array('name' => 'neuter', 'className' => 'fa fa-neuter'),
			array('name' => 'transgender', 'className' => 'fa fa-transgender'),
			array('name' => 'transgender-alt', 'className' => 'fa fa-transgender-alt'),
			array('name' => 'venus', 'className' => 'fa fa-venus'),
			array('name' => 'venus-double', 'className' => 'fa fa-venus-double'),
			array('name' => 'venus-mars', 'className' => 'fa fa-venus-mars'),
			array('name' => 'file', 'className' => 'fa fa-file'),
			array('name' => 'file-archive-o', 'className' => 'fa fa-file-archive-o'),
			array('name' => 'file-audio-o', 'className' => 'fa fa-file-audio-o'),
			array('name' => 'file-code-o', 'className' => 'fa fa-file-code-o'),
			array('name' => 'file-excel-o', 'className' => 'fa fa-file-excel-o'),
			array('name' => 'file-image-o', 'className' => 'fa fa-file-image-o'),
			array('name' => 'file-movie-o (alias)', 'className' => 'fa fa-file-movie-o'),
			array('name' => 'file-o', 'className' => 'fa fa-file-o'),
			array('name' => 'file-pdf-o', 'className' => 'fa fa-file-pdf-o'),
			array('name' => 'file-photo-o (alias)', 'className' => 'fa fa-file-photo-o'),
			array('name' => 'file-picture-o (alias)', 'className' => 'fa fa-file-picture-o'),
			array('name' => 'file-powerpoint-o', 'className' => 'fa fa-file-powerpoint-o'),
			array('name' => 'file-sound-o (alias)', 'className' => 'fa fa-file-sound-o'),
			array('name' => 'file-text', 'className' => 'fa fa-file-text'),
			array('name' => 'file-text-o', 'className' => 'fa fa-file-text-o'),
			array('name' => 'file-video-o', 'className' => 'fa fa-file-video-o'),
			array('name' => 'file-word-o', 'className' => 'fa fa-file-word-o'),
			array('name' => 'file-zip-o (alias)', 'className' => 'fa fa-file-zip-o'),
			array('name' => 'spinning icons example', 'className' => 'undefined'),
			array('name' => 'circle-o-notch', 'className' => 'fa fa-circle-o-notch'),
			array('name' => 'cog', 'className' => 'fa fa-cog'),
			array('name' => 'gear (alias)', 'className' => 'fa fa-gear'),
			array('name' => 'refresh', 'className' => 'fa fa-refresh'),
			array('name' => 'spinner', 'className' => 'fa fa-spinner'),
			array('name' => 'check-square', 'className' => 'fa fa-check-square'),
			array('name' => 'check-square-o', 'className' => 'fa fa-check-square-o'),
			array('name' => 'circle', 'className' => 'fa fa-circle'),
			array('name' => 'circle-o', 'className' => 'fa fa-circle-o'),
			array('name' => 'dot-circle-o', 'className' => 'fa fa-dot-circle-o'),
			array('name' => 'minus-square', 'className' => 'fa fa-minus-square'),
			array('name' => 'minus-square-o', 'className' => 'fa fa-minus-square-o'),
			array('name' => 'plus-square', 'className' => 'fa fa-plus-square'),
			array('name' => 'plus-square-o', 'className' => 'fa fa-plus-square-o'),
			array('name' => 'square', 'className' => 'fa fa-square'),
			array('name' => 'square-o', 'className' => 'fa fa-square-o'),
			array('name' => 'cc-amex', 'className' => 'fa fa-cc-amex'),
			array('name' => 'cc-diners-club', 'className' => 'fa fa-cc-diners-club'),
			array('name' => 'cc-discover', 'className' => 'fa fa-cc-discover'),
			array('name' => 'cc-jcb', 'className' => 'fa fa-cc-jcb'),
			array('name' => 'cc-mastercard', 'className' => 'fa fa-cc-mastercard'),
			array('name' => 'cc-paypal', 'className' => 'fa fa-cc-paypal'),
			array('name' => 'cc-stripe', 'className' => 'fa fa-cc-stripe'),
			array('name' => 'cc-visa', 'className' => 'fa fa-cc-visa'),
			array('name' => 'credit-card', 'className' => 'fa fa-credit-card'),
			array('name' => 'credit-card-alt', 'className' => 'fa fa-credit-card-alt'),
			array('name' => 'google-wallet', 'className' => 'fa fa-google-wallet'),
			array('name' => 'paypal', 'className' => 'fa fa-paypal'),
			array('name' => 'area-chart', 'className' => 'fa fa-area-chart'),
			array('name' => 'bar-chart', 'className' => 'fa fa-bar-chart'),
			array('name' => 'bar-chart-o (alias)', 'className' => 'fa fa-bar-chart-o'),
			array('name' => 'line-chart', 'className' => 'fa fa-line-chart'),
			array('name' => 'pie-chart', 'className' => 'fa fa-pie-chart'),
			array('name' => 'bitcoin (alias)', 'className' => 'fa fa-bitcoin'),
			array('name' => 'btc', 'className' => 'fa fa-btc'),
			array('name' => 'cny (alias)', 'className' => 'fa fa-cny'),
			array('name' => 'dollar (alias)', 'className' => 'fa fa-dollar'),
			array('name' => 'eur', 'className' => 'fa fa-eur'),
			array('name' => 'euro (alias)', 'className' => 'fa fa-euro'),
			array('name' => 'gbp', 'className' => 'fa fa-gbp'),
			array('name' => 'gg', 'className' => 'fa fa-gg'),
			array('name' => 'gg-circle', 'className' => 'fa fa-gg-circle'),
			array('name' => 'ils', 'className' => 'fa fa-ils'),
			array('name' => 'inr', 'className' => 'fa fa-inr'),
			array('name' => 'jpy', 'className' => 'fa fa-jpy'),
			array('name' => 'krw', 'className' => 'fa fa-krw'),
			array('name' => 'money', 'className' => 'fa fa-money'),
			array('name' => 'rmb (alias)', 'className' => 'fa fa-rmb'),
			array('name' => 'rouble (alias)', 'className' => 'fa fa-rouble'),
			array('name' => 'rub', 'className' => 'fa fa-rub'),
			array('name' => 'ruble (alias)', 'className' => 'fa fa-ruble'),
			array('name' => 'rupee (alias)', 'className' => 'fa fa-rupee'),
			array('name' => 'shekel (alias)', 'className' => 'fa fa-shekel'),
			array('name' => 'sheqel (alias)', 'className' => 'fa fa-sheqel'),
			array('name' => 'try', 'className' => 'fa fa-try'),
			array('name' => 'turkish-lira (alias)', 'className' => 'fa fa-turkish-lira'),
			array('name' => 'usd', 'className' => 'fa fa-usd'),
			array('name' => 'won (alias)', 'className' => 'fa fa-won'),
			array('name' => 'yen (alias)', 'className' => 'fa fa-yen'),
			array('name' => 'align-center', 'className' => 'fa fa-align-center'),
			array('name' => 'align-justify', 'className' => 'fa fa-align-justify'),
			array('name' => 'align-left', 'className' => 'fa fa-align-left'),
			array('name' => 'align-right', 'className' => 'fa fa-align-right'),
			array('name' => 'bold', 'className' => 'fa fa-bold'),
			array('name' => 'chain (alias)', 'className' => 'fa fa-chain'),
			array('name' => 'chain-broken', 'className' => 'fa fa-chain-broken'),
			array('name' => 'clipboard', 'className' => 'fa fa-clipboard'),
			array('name' => 'columns', 'className' => 'fa fa-columns'),
			array('name' => 'copy (alias)', 'className' => 'fa fa-copy'),
			array('name' => 'cut (alias)', 'className' => 'fa fa-cut'),
			array('name' => 'dedent (alias)', 'className' => 'fa fa-dedent'),
			array('name' => 'eraser', 'className' => 'fa fa-eraser'),
			array('name' => 'file', 'className' => 'fa fa-file'),
			array('name' => 'file-o', 'className' => 'fa fa-file-o'),
			array('name' => 'file-text', 'className' => 'fa fa-file-text'),
			array('name' => 'file-text-o', 'className' => 'fa fa-file-text-o'),
			array('name' => 'files-o', 'className' => 'fa fa-files-o'),
			array('name' => 'floppy-o', 'className' => 'fa fa-floppy-o'),
			array('name' => 'font', 'className' => 'fa fa-font'),
			array('name' => 'header', 'className' => 'fa fa-header'),
			array('name' => 'indent', 'className' => 'fa fa-indent'),
			array('name' => 'italic', 'className' => 'fa fa-italic'),
			array('name' => 'link', 'className' => 'fa fa-link'),
			array('name' => 'list', 'className' => 'fa fa-list'),
			array('name' => 'list-alt', 'className' => 'fa fa-list-alt'),
			array('name' => 'list-ol', 'className' => 'fa fa-list-ol'),
			array('name' => 'list-ul', 'className' => 'fa fa-list-ul'),
			array('name' => 'outdent', 'className' => 'fa fa-outdent'),
			array('name' => 'paperclip', 'className' => 'fa fa-paperclip'),
			array('name' => 'paragraph', 'className' => 'fa fa-paragraph'),
			array('name' => 'paste (alias)', 'className' => 'fa fa-paste'),
			array('name' => 'repeat', 'className' => 'fa fa-repeat'),
			array('name' => 'rotate-left (alias)', 'className' => 'fa fa-rotate-left'),
			array('name' => 'rotate-right (alias)', 'className' => 'fa fa-rotate-right'),
			array('name' => 'save (alias)', 'className' => 'fa fa-save'),
			array('name' => 'scissors', 'className' => 'fa fa-scissors'),
			array('name' => 'strikethrough', 'className' => 'fa fa-strikethrough'),
			array('name' => 'subscript', 'className' => 'fa fa-subscript'),
			array('name' => 'superscript', 'className' => 'fa fa-superscript'),
			array('name' => 'table', 'className' => 'fa fa-table'),
			array('name' => 'text-height', 'className' => 'fa fa-text-height'),
			array('name' => 'text-width', 'className' => 'fa fa-text-width'),
			array('name' => 'th', 'className' => 'fa fa-th'),
			array('name' => 'th-large', 'className' => 'fa fa-th-large'),
			array('name' => 'th-list', 'className' => 'fa fa-th-list'),
			array('name' => 'underline', 'className' => 'fa fa-underline'),
			array('name' => 'undo', 'className' => 'fa fa-undo'),
			array('name' => 'unlink (alias)', 'className' => 'fa fa-unlink'),
			array('name' => 'angle-double-down', 'className' => 'fa fa-angle-double-down'),
			array('name' => 'angle-double-left', 'className' => 'fa fa-angle-double-left'),
			array('name' => 'angle-double-right', 'className' => 'fa fa-angle-double-right'),
			array('name' => 'angle-double-up', 'className' => 'fa fa-angle-double-up'),
			array('name' => 'angle-down', 'className' => 'fa fa-angle-down'),
			array('name' => 'angle-left', 'className' => 'fa fa-angle-left'),
			array('name' => 'angle-right', 'className' => 'fa fa-angle-right'),
			array('name' => 'angle-up', 'className' => 'fa fa-angle-up'),
			array('name' => 'arrow-circle-down', 'className' => 'fa fa-arrow-circle-down'),
			array('name' => 'arrow-circle-left', 'className' => 'fa fa-arrow-circle-left'),
			array('name' => 'arrow-circle-o-down', 'className' => 'fa fa-arrow-circle-o-down'),
			array('name' => 'arrow-circle-o-left', 'className' => 'fa fa-arrow-circle-o-left'),
			array('name' => 'arrow-circle-o-right', 'className' => 'fa fa-arrow-circle-o-right'),
			array('name' => 'arrow-circle-o-up', 'className' => 'fa fa-arrow-circle-o-up'),
			array('name' => 'arrow-circle-right', 'className' => 'fa fa-arrow-circle-right'),
			array('name' => 'arrow-circle-up', 'className' => 'fa fa-arrow-circle-up'),
			array('name' => 'arrow-down', 'className' => 'fa fa-arrow-down'),
			array('name' => 'arrow-left', 'className' => 'fa fa-arrow-left'),
			array('name' => 'arrow-right', 'className' => 'fa fa-arrow-right'),
			array('name' => 'arrow-up', 'className' => 'fa fa-arrow-up'),
			array('name' => 'arrows', 'className' => 'fa fa-arrows'),
			array('name' => 'arrows-alt', 'className' => 'fa fa-arrows-alt'),
			array('name' => 'arrows-h', 'className' => 'fa fa-arrows-h'),
			array('name' => 'arrows-v', 'className' => 'fa fa-arrows-v'),
			array('name' => 'caret-down', 'className' => 'fa fa-caret-down'),
			array('name' => 'caret-left', 'className' => 'fa fa-caret-left'),
			array('name' => 'caret-right', 'className' => 'fa fa-caret-right'),
			array('name' => 'caret-square-o-down', 'className' => 'fa fa-caret-square-o-down'),
			array('name' => 'caret-square-o-left', 'className' => 'fa fa-caret-square-o-left'),
			array('name' => 'caret-square-o-right', 'className' => 'fa fa-caret-square-o-right'),
			array('name' => 'caret-square-o-up', 'className' => 'fa fa-caret-square-o-up'),
			array('name' => 'caret-up', 'className' => 'fa fa-caret-up'),
			array('name' => 'chevron-circle-down', 'className' => 'fa fa-chevron-circle-down'),
			array('name' => 'chevron-circle-left', 'className' => 'fa fa-chevron-circle-left'),
			array('name' => 'chevron-circle-right', 'className' => 'fa fa-chevron-circle-right'),
			array('name' => 'chevron-circle-up', 'className' => 'fa fa-chevron-circle-up'),
			array('name' => 'chevron-down', 'className' => 'fa fa-chevron-down'),
			array('name' => 'chevron-left', 'className' => 'fa fa-chevron-left'),
			array('name' => 'chevron-right', 'className' => 'fa fa-chevron-right'),
			array('name' => 'chevron-up', 'className' => 'fa fa-chevron-up'),
			array('name' => 'exchange', 'className' => 'fa fa-exchange'),
			array('name' => 'hand-o-down', 'className' => 'fa fa-hand-o-down'),
			array('name' => 'hand-o-left', 'className' => 'fa fa-hand-o-left'),
			array('name' => 'hand-o-right', 'className' => 'fa fa-hand-o-right'),
			array('name' => 'hand-o-up', 'className' => 'fa fa-hand-o-up'),
			array('name' => 'long-arrow-down', 'className' => 'fa fa-long-arrow-down'),
			array('name' => 'long-arrow-left', 'className' => 'fa fa-long-arrow-left'),
			array('name' => 'long-arrow-right', 'className' => 'fa fa-long-arrow-right'),
			array('name' => 'long-arrow-up', 'className' => 'fa fa-long-arrow-up'),
			array('name' => 'toggle-down (alias)', 'className' => 'fa fa-toggle-down'),
			array('name' => 'toggle-left (alias)', 'className' => 'fa fa-toggle-left'),
			array('name' => 'toggle-right (alias)', 'className' => 'fa fa-toggle-right'),
			array('name' => 'toggle-up (alias)', 'className' => 'fa fa-toggle-up'),
			array('name' => 'arrows-alt', 'className' => 'fa fa-arrows-alt'),
			array('name' => 'backward', 'className' => 'fa fa-backward'),
			array('name' => 'compress', 'className' => 'fa fa-compress'),
			array('name' => 'eject', 'className' => 'fa fa-eject'),
			array('name' => 'expand', 'className' => 'fa fa-expand'),
			array('name' => 'fast-backward', 'className' => 'fa fa-fast-backward'),
			array('name' => 'fast-forward', 'className' => 'fa fa-fast-forward'),
			array('name' => 'forward', 'className' => 'fa fa-forward'),
			array('name' => 'pause', 'className' => 'fa fa-pause'),
			array('name' => 'pause-circle', 'className' => 'fa fa-pause-circle'),
			array('name' => 'pause-circle-o', 'className' => 'fa fa-pause-circle-o'),
			array('name' => 'play', 'className' => 'fa fa-play'),
			array('name' => 'play-circle', 'className' => 'fa fa-play-circle'),
			array('name' => 'play-circle-o', 'className' => 'fa fa-play-circle-o'),
			array('name' => 'random', 'className' => 'fa fa-random'),
			array('name' => 'step-backward', 'className' => 'fa fa-step-backward'),
			array('name' => 'step-forward', 'className' => 'fa fa-step-forward'),
			array('name' => 'stop', 'className' => 'fa fa-stop'),
			array('name' => 'stop-circle', 'className' => 'fa fa-stop-circle'),
			array('name' => 'stop-circle-o', 'className' => 'fa fa-stop-circle-o'),
			array('name' => 'youtube-play', 'className' => 'fa fa-youtube-play'),
			array('name' => 'report an issue with Adblock Plus', 'className' => 'undefined'),
			array('name' => '500px', 'className' => 'fa fa-500px'),
			array('name' => 'adn', 'className' => 'fa fa-adn'),
			array('name' => 'amazon', 'className' => 'fa fa-amazon'),
			array('name' => 'android', 'className' => 'fa fa-android'),
			array('name' => 'angellist', 'className' => 'fa fa-angellist'),
			array('name' => 'apple', 'className' => 'fa fa-apple'),
			array('name' => 'behance', 'className' => 'fa fa-behance'),
			array('name' => 'behance-square', 'className' => 'fa fa-behance-square'),
			array('name' => 'bitbucket', 'className' => 'fa fa-bitbucket'),
			array('name' => 'bitbucket-square', 'className' => 'fa fa-bitbucket-square'),
			array('name' => 'bitcoin (alias)', 'className' => 'fa fa-bitcoin'),
			array('name' => 'black-tie', 'className' => 'fa fa-black-tie'),
			array('name' => 'bluetooth', 'className' => 'fa fa-bluetooth'),
			array('name' => 'bluetooth-b', 'className' => 'fa fa-bluetooth-b'),
			array('name' => 'btc', 'className' => 'fa fa-btc'),
			array('name' => 'buysellads', 'className' => 'fa fa-buysellads'),
			array('name' => 'cc-amex', 'className' => 'fa fa-cc-amex'),
			array('name' => 'cc-diners-club', 'className' => 'fa fa-cc-diners-club'),
			array('name' => 'cc-discover', 'className' => 'fa fa-cc-discover'),
			array('name' => 'cc-jcb', 'className' => 'fa fa-cc-jcb'),
			array('name' => 'cc-mastercard', 'className' => 'fa fa-cc-mastercard'),
			array('name' => 'cc-paypal', 'className' => 'fa fa-cc-paypal'),
			array('name' => 'cc-stripe', 'className' => 'fa fa-cc-stripe'),
			array('name' => 'cc-visa', 'className' => 'fa fa-cc-visa'),
			array('name' => 'chrome', 'className' => 'fa fa-chrome'),
			array('name' => 'codepen', 'className' => 'fa fa-codepen'),
			array('name' => 'codiepie', 'className' => 'fa fa-codiepie'),
			array('name' => 'connectdevelop', 'className' => 'fa fa-connectdevelop'),
			array('name' => 'contao', 'className' => 'fa fa-contao'),
			array('name' => 'css3', 'className' => 'fa fa-css3'),
			array('name' => 'dashcube', 'className' => 'fa fa-dashcube'),
			array('name' => 'delicious', 'className' => 'fa fa-delicious'),
			array('name' => 'deviantart', 'className' => 'fa fa-deviantart'),
			array('name' => 'digg', 'className' => 'fa fa-digg'),
			array('name' => 'dribbble', 'className' => 'fa fa-dribbble'),
			array('name' => 'dropbox', 'className' => 'fa fa-dropbox'),
			array('name' => 'drupal', 'className' => 'fa fa-drupal'),
			array('name' => 'edge', 'className' => 'fa fa-edge'),
			array('name' => 'empire', 'className' => 'fa fa-empire'),
			array('name' => 'envira', 'className' => 'fa fa-envira'),
			array('name' => 'expeditedssl', 'className' => 'fa fa-expeditedssl'),
			array('name' => 'fa (alias)', 'className' => 'fa fa-fa'),
			array('name' => 'facebook', 'className' => 'fa fa-facebook'),
			array('name' => 'facebook-f (alias)', 'className' => 'fa fa-facebook-f'),
			array('name' => 'facebook-official', 'className' => 'fa fa-facebook-official'),
			array('name' => 'facebook-square', 'className' => 'fa fa-facebook-square'),
			array('name' => 'firefox', 'className' => 'fa fa-firefox'),
			array('name' => 'first-order', 'className' => 'fa fa-first-order'),
			array('name' => 'flickr', 'className' => 'fa fa-flickr'),
			array('name' => 'font-awesome', 'className' => 'fa fa-font-awesome'),
			array('name' => 'fonticons', 'className' => 'fa fa-fonticons'),
			array('name' => 'fort-awesome', 'className' => 'fa fa-fort-awesome'),
			array('name' => 'forumbee', 'className' => 'fa fa-forumbee'),
			array('name' => 'foursquare', 'className' => 'fa fa-foursquare'),
			array('name' => 'ge (alias)', 'className' => 'fa fa-ge'),
			array('name' => 'get-pocket', 'className' => 'fa fa-get-pocket'),
			array('name' => 'gg', 'className' => 'fa fa-gg'),
			array('name' => 'gg-circle', 'className' => 'fa fa-gg-circle'),
			array('name' => 'git', 'className' => 'fa fa-git'),
			array('name' => 'git-square', 'className' => 'fa fa-git-square'),
			array('name' => 'github', 'className' => 'fa fa-github'),
			array('name' => 'github-alt', 'className' => 'fa fa-github-alt'),
			array('name' => 'github-square', 'className' => 'fa fa-github-square'),
			array('name' => 'gitlab', 'className' => 'fa fa-gitlab'),
			array('name' => 'gittip (alias)', 'className' => 'fa fa-gittip'),
			array('name' => 'glide', 'className' => 'fa fa-glide'),
			array('name' => 'glide-g', 'className' => 'fa fa-glide-g'),
			array('name' => 'google', 'className' => 'fa fa-google'),
			array('name' => 'google-plus', 'className' => 'fa fa-google-plus'),
			array('name' => 'google-plus-circle (alias)', 'className' => 'fa fa-google-plus-circle'),
			array('name' => 'google-plus-official', 'className' => 'fa fa-google-plus-official'),
			array('name' => 'google-plus-square', 'className' => 'fa fa-google-plus-square'),
			array('name' => 'google-wallet', 'className' => 'fa fa-google-wallet'),
			array('name' => 'gratipay', 'className' => 'fa fa-gratipay'),
			array('name' => 'hacker-news', 'className' => 'fa fa-hacker-news'),
			array('name' => 'houzz', 'className' => 'fa fa-houzz'),
			array('name' => 'html5', 'className' => 'fa fa-html5'),
			array('name' => 'instagram', 'className' => 'fa fa-instagram'),
			array('name' => 'internet-explorer', 'className' => 'fa fa-internet-explorer'),
			array('name' => 'ioxhost', 'className' => 'fa fa-ioxhost'),
			array('name' => 'joomla', 'className' => 'fa fa-joomla'),
			array('name' => 'jsfiddle', 'className' => 'fa fa-jsfiddle'),
			array('name' => 'lastfm', 'className' => 'fa fa-lastfm'),
			array('name' => 'lastfm-square', 'className' => 'fa fa-lastfm-square'),
			array('name' => 'leanpub', 'className' => 'fa fa-leanpub'),
			array('name' => 'linkedin', 'className' => 'fa fa-linkedin'),
			array('name' => 'linkedin-square', 'className' => 'fa fa-linkedin-square'),
			array('name' => 'linux', 'className' => 'fa fa-linux'),
			array('name' => 'maxcdn', 'className' => 'fa fa-maxcdn'),
			array('name' => 'meanpath', 'className' => 'fa fa-meanpath'),
			array('name' => 'medium', 'className' => 'fa fa-medium'),
			array('name' => 'mixcloud', 'className' => 'fa fa-mixcloud'),
			array('name' => 'modx', 'className' => 'fa fa-modx'),
			array('name' => 'odnoklassniki', 'className' => 'fa fa-odnoklassniki'),
			array('name' => 'odnoklassniki-square', 'className' => 'fa fa-odnoklassniki-square'),
			array('name' => 'opencart', 'className' => 'fa fa-opencart'),
			array('name' => 'openid', 'className' => 'fa fa-openid'),
			array('name' => 'opera', 'className' => 'fa fa-opera'),
			array('name' => 'optin-monster', 'className' => 'fa fa-optin-monster'),
			array('name' => 'pagelines', 'className' => 'fa fa-pagelines'),
			array('name' => 'paypal', 'className' => 'fa fa-paypal'),
			array('name' => 'pied-piper', 'className' => 'fa fa-pied-piper'),
			array('name' => 'pied-piper-alt', 'className' => 'fa fa-pied-piper-alt'),
			array('name' => 'pied-piper-pp', 'className' => 'fa fa-pied-piper-pp'),
			array('name' => 'pinterest', 'className' => 'fa fa-pinterest'),
			array('name' => 'pinterest-p', 'className' => 'fa fa-pinterest-p'),
			array('name' => 'pinterest-square', 'className' => 'fa fa-pinterest-square'),
			array('name' => 'product-hunt', 'className' => 'fa fa-product-hunt'),
			array('name' => 'qq', 'className' => 'fa fa-qq'),
			array('name' => 'ra (alias)', 'className' => 'fa fa-ra'),
			array('name' => 'rebel', 'className' => 'fa fa-rebel'),
			array('name' => 'reddit', 'className' => 'fa fa-reddit'),
			array('name' => 'reddit-alien', 'className' => 'fa fa-reddit-alien'),
			array('name' => 'reddit-square', 'className' => 'fa fa-reddit-square'),
			array('name' => 'renren', 'className' => 'fa fa-renren'),
			array('name' => 'resistance (alias)', 'className' => 'fa fa-resistance'),
			array('name' => 'safari', 'className' => 'fa fa-safari'),
			array('name' => 'scribd', 'className' => 'fa fa-scribd'),
			array('name' => 'sellsy', 'className' => 'fa fa-sellsy'),
			array('name' => 'share-alt', 'className' => 'fa fa-share-alt'),
			array('name' => 'share-alt-square', 'className' => 'fa fa-share-alt-square'),
			array('name' => 'shirtsinbulk', 'className' => 'fa fa-shirtsinbulk'),
			array('name' => 'simplybuilt', 'className' => 'fa fa-simplybuilt'),
			array('name' => 'skyatlas', 'className' => 'fa fa-skyatlas'),
			array('name' => 'skype', 'className' => 'fa fa-skype'),
			array('name' => 'slack', 'className' => 'fa fa-slack'),
			array('name' => 'slideshare', 'className' => 'fa fa-slideshare'),
			array('name' => 'snapchat', 'className' => 'fa fa-snapchat'),
			array('name' => 'snapchat-ghost', 'className' => 'fa fa-snapchat-ghost'),
			array('name' => 'snapchat-square', 'className' => 'fa fa-snapchat-square'),
			array('name' => 'soundcloud', 'className' => 'fa fa-soundcloud'),
			array('name' => 'spotify', 'className' => 'fa fa-spotify'),
			array('name' => 'stack-exchange', 'className' => 'fa fa-stack-exchange'),
			array('name' => 'stack-overflow', 'className' => 'fa fa-stack-overflow'),
			array('name' => 'steam', 'className' => 'fa fa-steam'),
			array('name' => 'steam-square', 'className' => 'fa fa-steam-square'),
			array('name' => 'stumbleupon', 'className' => 'fa fa-stumbleupon'),
			array('name' => 'stumbleupon-circle', 'className' => 'fa fa-stumbleupon-circle'),
			array('name' => 'tencent-weibo', 'className' => 'fa fa-tencent-weibo'),
			array('name' => 'themeisle', 'className' => 'fa fa-themeisle'),
			array('name' => 'trello', 'className' => 'fa fa-trello'),
			array('name' => 'tripadvisor', 'className' => 'fa fa-tripadvisor'),
			array('name' => 'tumblr', 'className' => 'fa fa-tumblr'),
			array('name' => 'tumblr-square', 'className' => 'fa fa-tumblr-square'),
			array('name' => 'twitch', 'className' => 'fa fa-twitch'),
			array('name' => 'twitter', 'className' => 'fa fa-twitter'),
			array('name' => 'twitter-square', 'className' => 'fa fa-twitter-square'),
			array('name' => 'usb', 'className' => 'fa fa-usb'),
			array('name' => 'viacoin', 'className' => 'fa fa-viacoin'),
			array('name' => 'viadeo', 'className' => 'fa fa-viadeo'),
			array('name' => 'viadeo-square', 'className' => 'fa fa-viadeo-square'),
			array('name' => 'vimeo', 'className' => 'fa fa-vimeo'),
			array('name' => 'vimeo-square', 'className' => 'fa fa-vimeo-square'),
			array('name' => 'vine', 'className' => 'fa fa-vine'),
			array('name' => 'vk', 'className' => 'fa fa-vk'),
			array('name' => 'wechat (alias)', 'className' => 'fa fa-wechat'),
			array('name' => 'weibo', 'className' => 'fa fa-weibo'),
			array('name' => 'weixin', 'className' => 'fa fa-weixin'),
			array('name' => 'whatsapp', 'className' => 'fa fa-whatsapp'),
			array('name' => 'wikipedia-w', 'className' => 'fa fa-wikipedia-w'),
			array('name' => 'windows', 'className' => 'fa fa-windows'),
			array('name' => 'wordpress', 'className' => 'fa fa-wordpress'),
			array('name' => 'wpbeginner', 'className' => 'fa fa-wpbeginner'),
			array('name' => 'wpforms', 'className' => 'fa fa-wpforms'),
			array('name' => 'xing', 'className' => 'fa fa-xing'),
			array('name' => 'xing-square', 'className' => 'fa fa-xing-square'),
			array('name' => 'y-combinator', 'className' => 'fa fa-y-combinator'),
			array('name' => 'y-combinator-square (alias)', 'className' => 'fa fa-y-combinator-square'),
			array('name' => 'yahoo', 'className' => 'fa fa-yahoo'),
			array('name' => 'yc (alias)', 'className' => 'fa fa-yc'),
			array('name' => 'yc-square (alias)', 'className' => 'fa fa-yc-square'),
			array('name' => 'yelp', 'className' => 'fa fa-yelp'),
			array('name' => 'yoast', 'className' => 'fa fa-yoast'),
			array('name' => 'youtube', 'className' => 'fa fa-youtube'),
			array('name' => 'youtube-play', 'className' => 'fa fa-youtube-play'),
			array('name' => 'youtube-square', 'className' => 'fa fa-youtube-square'),
			array('name' => 'ambulance', 'className' => 'fa fa-ambulance'),
			array('name' => 'h-square', 'className' => 'fa fa-h-square'),
			array('name' => 'heart', 'className' => 'fa fa-heart'),
			array('name' => 'heart-o', 'className' => 'fa fa-heart-o'),
			array('name' => 'heartbeat', 'className' => 'fa fa-heartbeat'),
			array('name' => 'hospital-o', 'className' => 'fa fa-hospital-o'),
			array('name' => 'medkit', 'className' => 'fa fa-medkit'),
			array('name' => 'plus-square', 'className' => 'fa fa-plus-square'),
			array('name' => 'stethoscope', 'className' => 'fa fa-stethoscope'),
			array('name' => 'user-md', 'className' => 'fa fa-user-md'),
			array('name' => 'wheelchair', 'className' => 'fa fa-wheelchair'),
			array('name' => 'wheelchair-alt', 'className' => 'fa fa-wheelchair-alt'),
		),
	);

	return $icons;
}
